# Generated by Django 5.2.13 on 2026-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response1', models.TextField()),
                ('response2', models.TextField()),
                ('accuracy', models.IntegerField()),
                ('relevance', models.IntegerField()),
                ('coherence', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
